### ISSUE TITLE
Add publications back

### ISSUE THREAD

**Issue by CJ-Wright** [Billingegroup/rg-db-public#110]
I'm not certain why they were deleted in the first place.

**Comment by sbillinge** [comment]
I cleaned out all dbs that were not validating at some point to try and get validation working.....

**Comment by sbillinge** [comment]
here is the curent status...
```
$ regolith validate
~\dbs\rg-db-public\_build\_dbs\billingegroup-public ~\dbs\rg-db-public
remote: Counting objects: 17, done.
remote: Compressing objects: 100% (8/8), done.
remote: Total 17 (delta 9), reused 16 (delta 9), pack-reused 0
Unpacking objects: 100% (17/17), done.
From github.com:Billingegroup/rg-db-public
 * branch            master     -> FETCH_HEAD
   33dab83..468fad0  master     -> upstream/master
Updating 33dab83..468fad0
Fast-forward
 db/institutions.yml | 7 +++++++
 db/people.yml       | 7 +++++--
 2 files changed, 12 insertions(+), 2 deletions(-)
~\dbs\rg-db-public
~\dbs\rg-db-public\_build\_dbs\billingegroup-public ~\dbs\rg-db-public
~\dbs\rg-db-public
~\dbs\rg-db-public\_build\_dbs\billingegroup-public ~\dbs\rg-db-public
==========
VALIDATING


NO ERRORS IN DBS
===============
Nothing specified, nothing added.
Maybe you wanted to say 'git add .'?
~\dbs\rg-db-public
~\dbs\rg-db-public\_build\_dbs\billingegroup-public ~\dbs\rg-db-public
On branch master
Your branch and 'origin/master' have diverged,
and have 38 and 14 different commits each, respectively.
  (use "git pull" to merge the remote branch into yours)
Untracked files:
        ../../../dbdir/

nothing added to commit but untracked files present
Traceback (most recent call last):
  File "C:/Users/simon/Anaconda3/envs/bg/Scripts/regolith", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "C:\Users\simon\dev\regolith\scripts\regolith", line 3, in <module>
    main()
  File "c:\users\simon\dev\regolith\regolith\main.py", line 254, in main
    CONNECTED_COMMANDS[rc.cmd](rc)
  File "C:\Users\simon\Anaconda3\envs\bg\lib\contextlib.py", line 66, in __exit__
    next(self.gen)
  File "c:\users\simon\dev\regolith\regolith\database.xsh", line 186, in connect
    dump_database(db, client, rc)
  File "c:\users\simon\dev\regolith\regolith\database.xsh", line 139, in dump_database
    dump_git_database(db, client, rc)
  File "c:\users\simon\dev\regolith\regolith\database.xsh", line 98, in dump_git_database
    subprocess.check_call(cmd, cwd=dbdir)
  File "C:\Users\simon\Anaconda3\envs\bg\lib\site-packages\xonsh\lib\subprocess.xsh", line 20, in check_call
    p = run(cmd, cwd=cwd, check=True)
  File "C:\Users\simon\Anaconda3\envs\bg\lib\site-packages\xonsh\lib\subprocess.xsh", line 14, in run
    p = ![@(cmd)]
  File "C:\Users\simon\Anaconda3\envs\bg\lib\site-packages\xonsh\__amalgam__.py", line 19553, in subproc_captured_hiddenobject
    return run_subproc(cmds, captured='hiddenobject')
  File "C:\Users\simon\Anaconda3\envs\bg\lib\site-packages\xonsh\__amalgam__.py", line 19516, in run_subproc
    command.end()
  File "C:\Users\simon\Anaconda3\envs\bg\lib\site-packages\xonsh\__amalgam__.py", line 12724, in end
    self._end(tee_output=tee_output)
  File "C:\Users\simon\Anaconda3\envs\bg\lib\site-packages\xonsh\__amalgam__.py", line 12743, in _end
    self._raise_subproc_error()
  File "C:\Users\simon\Anaconda3\envs\bg\lib\site-packages\xonsh\__amalgam__.py", line 12864, in _raise_subproc_error
    output=self.output)
subprocess.CalledProcessError: Command '['C:\\Program Files\\Git\\mingw64\\bin\\git.exe', 'commit', '-m', 'regolith auto-commit']' returned non-zero exit status 1
```

**Comment by CJ-Wright** [comment]
Can you update your xonsh? The new version fixed some things. I'm also working on 2 bug fix PRs for things that were revealed after the new version of xonsh came out.

**Comment by sbillinge** [comment]
interesting, getting a xonsh error...
```
simon@LAPTOP-FU6OME5O MINGW64 ~/dbs/rg-db-public (master)
$ regolith validate
~\dbs\rg-db-public\_build\_dbs\billingegroup-public ~\dbs\rg-db-public
From github.com:Billingegroup/rg-db-public
 * branch            master     -> FETCH_HEAD
Already up-to-date.
~\dbs\rg-db-public
~\dbs\rg-db-public\_build\_dbs\billingegroup-public ~\dbs\rg-db-public
~\dbs\rg-db-public
~\dbs\rg-db-public\_build\_dbs\billingegroup-public ~\dbs\rg-db-public
==========
VALIDATING


NO ERRORS IN DBS
===============
Nothing specified, nothing added.
Maybe you wanted to say 'git add .'?
~\dbs\rg-db-public
~\dbs\rg-db-public\_build\_dbs\billingegroup-public ~\dbs\rg-db-public
On branch master
Your branch and 'origin/master' have diverged,
and have 38 and 14 different commits each, respectively.
  (use "git pull" to merge the remote branch into yours)
Untracked files:
        ../../../dbdir/

nothing added to commit but untracked files present
~\dbs\rg-db-public
Traceback (most recent call last):
  File "C:\Users\simon\Anaconda3\envs\bg\lib\site-packages\xonsh\__amalgam__.py", line 16328, in swap
    yield self
  File "C:\Users\simon\Anaconda3\envs\bg\lib\site-packages\xonsh\lib\subprocess.xsh", line 14, in run
    p = ![@(cmd)]
  File "C:\Users\simon\Anaconda3\envs\bg\lib\site-packages\xonsh\__amalgam__.py", line 19776, in subproc_captured_hiddenobject
    return run_subproc(cmds, captured='hiddenobject')
  File "C:\Users\simon\Anaconda3\envs\bg\lib\site-packages\xonsh\__amalgam__.py", line 19739, in run_subproc
    command.end()
  File "C:\Users\simon\Anaconda3\envs\bg\lib\site-packages\xonsh\__amalgam__.py", line 12899, in end
    self._end(tee_output=tee_output)
  File "C:\Users\simon\Anaconda3\envs\bg\lib\site-packages\xonsh\__amalgam__.py", line 12918, in _end
    self._raise_subproc_error()
  File "C:\Users\simon\Anaconda3\envs\bg\lib\site-packages\xonsh\__amalgam__.py", line 13039, in _raise_subproc_error
    output=self.output)
subprocess.CalledProcessError: Command '['C:\\Program Files\\Git\\mingw64\\bin\\git.exe', 'commit', '-m', 'regolith auto-commit']' returned non-zero exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/simon/Anaconda3/envs/bg/Scripts/regolith", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "C:\Users\simon\dev\regolith\scripts\regolith", line 3, in <module>
    main()
  File "c:\users\simon\dev\regolith\regolith\main.py", line 254, in main
    CONNECTED_COMMANDS[rc.cmd](rc)
  File "C:\Users\simon\Anaconda3\envs\bg\lib\contextlib.py", line 66, in __exit__
    next(self.gen)
  File "c:\users\simon\dev\regolith\regolith\database.xsh", line 186, in connect
    dump_database(db, client, rc)
  File "c:\users\simon\dev\regolith\regolith\database.xsh", line 139, in dump_database
    dump_git_database(db, client, rc)
  File "c:\users\simon\dev\regolith\regolith\database.xsh", line 98, in dump_git_database
    subprocess.check_call(cmd, cwd=dbdir)
  File "C:\Users\simon\Anaconda3\envs\bg\lib\site-packages\xonsh\lib\subprocess.xsh", line 20, in check_call
    p = run(cmd, cwd=cwd, check=True)
  File "C:\Users\simon\Anaconda3\envs\bg\lib\site-packages\xonsh\lib\subprocess.xsh", line 14, in run
    p = ![@(cmd)]
  File "C:\Users\simon\Anaconda3\envs\bg\lib\contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "C:\Users\simon\Anaconda3\envs\bg\lib\site-packages\xonsh\__amalgam__.py", line 16338, in swap
    if exception is not None:
UnboundLocalError: local variable 'exception' referenced before assignment
```

**Comment by CJ-Wright** [comment]
Would you mind cross referencing this to xonsh?

**Comment by CJ-Wright** [comment]
I think this is ok now.

**Comment by sbillinge** [comment]
thanks @CJ-Wright
